### PR TITLE
put(Collection<?>) method is added to conform old json library

### PR DESCRIPTION
**Pull request by solomax**
Would appreciate if you can release library with this addition :)

### CODE REVIEW

**Comment by tdunning** [comment]
Looks good to me.

LGTM

**Comment by solomax** [comment]
Thanks!
Do you have any roadmap for releases?

**Comment by tdunning** [comment]
On Fri, Dec 2, 2016 at 7:09 PM, Maxim Solodovnik <notifications@github.com>
wrote:

> Do you have any roadmap for releases?
>
>
Not really. This isn't really a project ... it is a temporary measure that
people can use as they move to something modern like Jackson.

That said, as people need updates to help stop using json.org stuff, I am
happy to help with that.

So, I guess that the nice way to say it is that this will be "community
driven".

**Comment by solomax** [comment]
Could you please release this version?

**Comment by tdunning** [comment]
Just did although I haven't seen it appear on central yet.

Also added some other changes.

**Comment by solomax** [comment]
Thanks a lot!

**Pull request merged**
