### PR TITLE
JSONFunction / Slash escape / JDK 1.5

### PR DESCRIPTION
**Pull request by klopfdreh**
* JSONFunction class for value as a hack to not surround it with quotes
* Only escape "/" slash after a "<" bracket, because it is allowed
* JDK 1.5

### CODE REVIEW

**Comment by klopfdreh** [comment]
Hi,

as long as no Java 7 features are needed I would suggest to compile on Java 1.5 (we need that target version for Apache Wicket: https://github.com/apache/wicket)

I have implemented a small hack - see the new test.

Also as of http://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped slashes are allowed, but only escaped right after a "<" bracket. The reason is that you can't place them into a script-tag without.

formatting is retained.

**Comment by klopfdreh** [comment]
https://issues.apache.org/jira/browse/WICKET-6287

**Comment by martin-g** [comment]
@klopfdreh 
- Wicket 1.5 does not use JSON.org. We started using it from 6.0.0, i.e. it should be compiled with target 1.6.
- JsonFunction is not in JSON specs. As mentioned at https://github.com/apache/wicket/blob/ce66c242ad83266a4f5c01363b4b446138b054e9/wicket-core/src/main/java/org/apache/wicket/ajax/json/README#L9 all `Json**` (in contrast to `JSON**`) classes are developed for Wicket's needs in addition.

**Comment by klopfdreh** [comment]
* If the lib also compiles with JDK 1.5 why not use this instead of 1.6 - it covers even more Apps using 1.5 currently
* I am going to rename it back and change the build in hack back to JsonFunction - it is just a hack to let JSONStringer not surround the value with quotes

**Comment by martin-g** [comment]
If someone still uses Java 5 for whatever reasons I'm pretty sure that (s)he won't want to change the JSON lib just for the fun :-)

**Review by tdunning — COMMENTED** [review]
It seems that we have two or three changes here.

1) revert to 1.5

2) quote the / under certain circumstances

3) omit quotes in special cases

Shouldn't these be split into three changes?

Also, strange hacks such as (3) may well not be acceptable to others. Do you think that the impact is small enough that nobody will have a problem? Or should we introduce an options mechanism?

**Comment by tdunning** [comment]
Regarding support for java 1.5, I would rather not go that far. For one thing, my Java compiler warns me about that and I prefer to avoid warnings.

**Comment by tdunning** [comment]
OK. I have incorporated the Java level change (but only to 1.6) and the </ escaping since I think that nobody can mind those changes. I did those as separate commits to make them more clear.

The function non-quoting is still not clear to me. Can you merge my changes so far into your code so that we can look at the differences more clearly?

And can you say a bit more about the intent? Is it to have a special purpose hack so that if the value of an object is a class with JSONFunction in the name that quotes will not be used for toString? No change on deserialization?

**Comment by klopfdreh** [comment]
Hi,

first of all - thanks for your fast response! - 1.6 is also fine for Apache Wicket and if you get compiler warnings we should avoid to use 1.5.

Regarding the JSONFunction:

This is only a separate behavior in case that the values class name contains JSONFunction* and causes them not to be surrounded by quotes. I wrote a test case for that:

https://github.com/klopfdreh/open-json/blob/455dce4e03ebdb12b758d3b0b4b89391746841dd/src/test/java/org/json/JSONStringerTest.java#L29

I explained the code in this line:

https://github.com/klopfdreh/open-json/blob/455dce4e03ebdb12b758d3b0b4b89391746841dd/src/main/java/org/json/JSONStringer.java#L259

It does not affect other users, because the value is checked for a specific class name.

I would suggest to implement it that way, because you can use it without a special flag - it is used per value.

**Comment by tdunning** [comment]
Check out master branch and let me know if this meets your needs.

Once you give the word, I will push a new release.

**Comment by klopfdreh** [comment]
Hi @tdunning - yes looks good to me. I just saw that the method "string" is private - so no need to implement one without the second parameter.

Thank you!

**Comment by tdunning** [comment]
Release is done.  Look for version 1.2 on central in a few hours.

**Comment by klopfdreh** [comment]
Thank you! 👍

**Pull request closed without merging**
